[package]
name = "cargo-mrepo"
version = "0.1.0"
authors = ["YushiOMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
walkdir = "2.3"
anyhow = "1.0"
cargo_metadata = "0.11"
